# Generated by Django 3.2.4 on 2021-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
